<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_invite</name>
   <tag></tag>
   <elementGuidId>76336dfd-beee-47b3-82c8-f7d17a87d492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form</value>
   </webElementProperties>
</WebElementEntity>
