<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_EmergencyPhone</name>
   <tag></tag>
   <elementGuidId>94b0ccbc-c9ea-431e-a7b0-f908a2ce05f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder='xxx-xxx-xxxx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@placeholder='xxx-xxx-xxxx']</value>
   </webElementProperties>
</WebElementEntity>
