<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Homeowner</name>
   <tag></tag>
   <elementGuidId>b9b18406-e30b-4eb6-9164-a5ac4940e43f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label/span[text()='homeowner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label/span[text()='homeowner']</value>
   </webElementProperties>
</WebElementEntity>
