<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_RequestType</name>
   <tag></tag>
   <elementGuidId>64477b1f-de34-4a0a-a78d-4820ef0d358b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul/li[contains(text(),'${request_type}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul/li[contains(text(),'${request_type}')]</value>
   </webElementProperties>
</WebElementEntity>
