<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_Project</name>
   <tag></tag>
   <elementGuidId>1f3c19de-af23-410c-9587-2811a3e26fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul/li[contains(text(),'${project_name}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul/li[contains(text(),'${project_name}')]</value>
   </webElementProperties>
</WebElementEntity>
