<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_Lot</name>
   <tag></tag>
   <elementGuidId>13af8990-c560-4dd0-9ebc-f9ac8bfc470a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul/li[contains(text(),'${lot_id}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul/li[contains(text(),'${lot_id}')]</value>
   </webElementProperties>
</WebElementEntity>
