<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_WOType</name>
   <tag></tag>
   <elementGuidId>c7e531f8-a632-45a5-97ad-a4cc9e904e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul/li[contains(text(),'${WO_Type}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul/li[contains(text(),'${WO_Type}')]</value>
   </webElementProperties>
</WebElementEntity>
